// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shin.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EShinResult int32

const (
	EShinResult_LOGIN_SUCCESS EShinResult = 0
	EShinResult_LOGIN_FAIL    EShinResult = 1
)

var EShinResult_name = map[int32]string{
	0: "LOGIN_SUCCESS",
	1: "LOGIN_FAIL",
}
var EShinResult_value = map[string]int32{
	"LOGIN_SUCCESS": 0,
	"LOGIN_FAIL":    1,
}

func (x EShinResult) Enum() *EShinResult {
	p := new(EShinResult)
	*p = x
	return p
}
func (x EShinResult) String() string {
	return proto.EnumName(EShinResult_name, int32(x))
}
func (x *EShinResult) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EShinResult_value, data, "EShinResult")
	if err != nil {
		return err
	}
	*x = EShinResult(value)
	return nil
}
func (EShinResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_shin_c01db11e994b0a2e, []int{0}
}

type EShinGender int32

const (
	EShinGender_GENDER_NULL   EShinGender = 0
	EShinGender_GENDER_MALE   EShinGender = 1
	EShinGender_GENDER_FEMAIL EShinGender = 2
)

var EShinGender_name = map[int32]string{
	0: "GENDER_NULL",
	1: "GENDER_MALE",
	2: "GENDER_FEMAIL",
}
var EShinGender_value = map[string]int32{
	"GENDER_NULL":   0,
	"GENDER_MALE":   1,
	"GENDER_FEMAIL": 2,
}

func (x EShinGender) Enum() *EShinGender {
	p := new(EShinGender)
	*p = x
	return p
}
func (x EShinGender) String() string {
	return proto.EnumName(EShinGender_name, int32(x))
}
func (x *EShinGender) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EShinGender_value, data, "EShinGender")
	if err != nil {
		return err
	}
	*x = EShinGender(value)
	return nil
}
func (EShinGender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_shin_c01db11e994b0a2e, []int{1}
}

type EShinPlayerAttr int32

const (
	EShinPlayerAttr_PLAYER_ATTR_NAME         EShinPlayerAttr = 3
	EShinPlayerAttr_PLAYER_ATTR_GENDER       EShinPlayerAttr = 4
	EShinPlayerAttr_PLAYER_ATTR_AVATAR       EShinPlayerAttr = 5
	EShinPlayerAttr_PLAYER_ATTR_GOLD         EShinPlayerAttr = 6
	EShinPlayerAttr_PLAYER_ATTR_GEMS         EShinPlayerAttr = 7
	EShinPlayerAttr_PLAYER_ATTR_PH           EShinPlayerAttr = 8
	EShinPlayerAttr_PLAYER_ATTR_PVP_DIVISION EShinPlayerAttr = 9
	EShinPlayerAttr_PLAYER_ATTR_PVP_STAR     EShinPlayerAttr = 10
	EShinPlayerAttr_PLAYER_ATTR_PVP_SCORE    EShinPlayerAttr = 11
	EShinPlayerAttr_PLAYER_ATTR_CHAT_SESSION EShinPlayerAttr = 12
	EShinPlayerAttr_PLAYER_ATTR_PH_CONFIRM   EShinPlayerAttr = 14
	EShinPlayerAttr_PLAYER_ATTR_PH_LIST      EShinPlayerAttr = 15
)

var EShinPlayerAttr_name = map[int32]string{
	3:  "PLAYER_ATTR_NAME",
	4:  "PLAYER_ATTR_GENDER",
	5:  "PLAYER_ATTR_AVATAR",
	6:  "PLAYER_ATTR_GOLD",
	7:  "PLAYER_ATTR_GEMS",
	8:  "PLAYER_ATTR_PH",
	9:  "PLAYER_ATTR_PVP_DIVISION",
	10: "PLAYER_ATTR_PVP_STAR",
	11: "PLAYER_ATTR_PVP_SCORE",
	12: "PLAYER_ATTR_CHAT_SESSION",
	14: "PLAYER_ATTR_PH_CONFIRM",
	15: "PLAYER_ATTR_PH_LIST",
}
var EShinPlayerAttr_value = map[string]int32{
	"PLAYER_ATTR_NAME":         3,
	"PLAYER_ATTR_GENDER":       4,
	"PLAYER_ATTR_AVATAR":       5,
	"PLAYER_ATTR_GOLD":         6,
	"PLAYER_ATTR_GEMS":         7,
	"PLAYER_ATTR_PH":           8,
	"PLAYER_ATTR_PVP_DIVISION": 9,
	"PLAYER_ATTR_PVP_STAR":     10,
	"PLAYER_ATTR_PVP_SCORE":    11,
	"PLAYER_ATTR_CHAT_SESSION": 12,
	"PLAYER_ATTR_PH_CONFIRM":   14,
	"PLAYER_ATTR_PH_LIST":      15,
}

func (x EShinPlayerAttr) Enum() *EShinPlayerAttr {
	p := new(EShinPlayerAttr)
	*p = x
	return p
}
func (x EShinPlayerAttr) String() string {
	return proto.EnumName(EShinPlayerAttr_name, int32(x))
}
func (x *EShinPlayerAttr) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EShinPlayerAttr_value, data, "EShinPlayerAttr")
	if err != nil {
		return err
	}
	*x = EShinPlayerAttr(value)
	return nil
}
func (EShinPlayerAttr) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_shin_c01db11e994b0a2e, []int{2}
}

type EShinOnline int32

const (
	// 离线
	EShinOnline_SHIN_OFFLINE EShinOnline = 0
	// 在线
	EShinOnline_SHIN_ONLINE EShinOnline = 1
)

var EShinOnline_name = map[int32]string{
	0: "SHIN_OFFLINE",
	1: "SHIN_ONLINE",
}
var EShinOnline_value = map[string]int32{
	"SHIN_OFFLINE": 0,
	"SHIN_ONLINE":  1,
}

func (x EShinOnline) Enum() *EShinOnline {
	p := new(EShinOnline)
	*p = x
	return p
}
func (x EShinOnline) String() string {
	return proto.EnumName(EShinOnline_name, int32(x))
}
func (x *EShinOnline) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EShinOnline_value, data, "EShinOnline")
	if err != nil {
		return err
	}
	*x = EShinOnline(value)
	return nil
}
func (EShinOnline) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_shin_c01db11e994b0a2e, []int{3}
}

// 10
type C2SLogin struct {
	Accname              *string  `protobuf:"bytes,1,req,name=accname" json:"accname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SLogin) Reset()         { *m = C2SLogin{} }
func (m *C2SLogin) String() string { return proto.CompactTextString(m) }
func (*C2SLogin) ProtoMessage()    {}
func (*C2SLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_c01db11e994b0a2e, []int{0}
}
func (m *C2SLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SLogin.Unmarshal(m, b)
}
func (m *C2SLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SLogin.Marshal(b, m, deterministic)
}
func (dst *C2SLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SLogin.Merge(dst, src)
}
func (m *C2SLogin) XXX_Size() int {
	return xxx_messageInfo_C2SLogin.Size(m)
}
func (m *C2SLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SLogin.DiscardUnknown(m)
}

var xxx_messageInfo_C2SLogin proto.InternalMessageInfo

func (m *C2SLogin) GetAccname() string {
	if m != nil && m.Accname != nil {
		return *m.Accname
	}
	return ""
}

// 11
type S2CLogin struct {
	Ret                  *int32   `protobuf:"varint,1,req,name=ret" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CLogin) Reset()         { *m = S2CLogin{} }
func (m *S2CLogin) String() string { return proto.CompactTextString(m) }
func (*S2CLogin) ProtoMessage()    {}
func (*S2CLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_c01db11e994b0a2e, []int{1}
}
func (m *S2CLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CLogin.Unmarshal(m, b)
}
func (m *S2CLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CLogin.Marshal(b, m, deterministic)
}
func (dst *S2CLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CLogin.Merge(dst, src)
}
func (m *S2CLogin) XXX_Size() int {
	return xxx_messageInfo_S2CLogin.Size(m)
}
func (m *S2CLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CLogin.DiscardUnknown(m)
}

var xxx_messageInfo_S2CLogin proto.InternalMessageInfo

func (m *S2CLogin) GetRet() int32 {
	if m != nil && m.Ret != nil {
		return *m.Ret
	}
	return 0
}

// 101   pf:android/ios
type CPlayerLogin struct {
	Session              *string  `protobuf:"bytes,1,req,name=session" json:"session,omitempty"`
	Pf                   *string  `protobuf:"bytes,2,req,name=pf" json:"pf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CPlayerLogin) Reset()         { *m = CPlayerLogin{} }
func (m *CPlayerLogin) String() string { return proto.CompactTextString(m) }
func (*CPlayerLogin) ProtoMessage()    {}
func (*CPlayerLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_c01db11e994b0a2e, []int{2}
}
func (m *CPlayerLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CPlayerLogin.Unmarshal(m, b)
}
func (m *CPlayerLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CPlayerLogin.Marshal(b, m, deterministic)
}
func (dst *CPlayerLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CPlayerLogin.Merge(dst, src)
}
func (m *CPlayerLogin) XXX_Size() int {
	return xxx_messageInfo_CPlayerLogin.Size(m)
}
func (m *CPlayerLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_CPlayerLogin.DiscardUnknown(m)
}

var xxx_messageInfo_CPlayerLogin proto.InternalMessageInfo

func (m *CPlayerLogin) GetSession() string {
	if m != nil && m.Session != nil {
		return *m.Session
	}
	return ""
}

func (m *CPlayerLogin) GetPf() string {
	if m != nil && m.Pf != nil {
		return *m.Pf
	}
	return ""
}

// 102
type SPlayerLogin struct {
	Result               *EShinResult `protobuf:"varint,1,req,name=result,enum=proto.EShinResult" json:"result,omitempty"`
	PlayerId             *uint32      `protobuf:"varint,2,req,name=player_id,json=playerId" json:"player_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SPlayerLogin) Reset()         { *m = SPlayerLogin{} }
func (m *SPlayerLogin) String() string { return proto.CompactTextString(m) }
func (*SPlayerLogin) ProtoMessage()    {}
func (*SPlayerLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_c01db11e994b0a2e, []int{3}
}
func (m *SPlayerLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SPlayerLogin.Unmarshal(m, b)
}
func (m *SPlayerLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SPlayerLogin.Marshal(b, m, deterministic)
}
func (dst *SPlayerLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SPlayerLogin.Merge(dst, src)
}
func (m *SPlayerLogin) XXX_Size() int {
	return xxx_messageInfo_SPlayerLogin.Size(m)
}
func (m *SPlayerLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_SPlayerLogin.DiscardUnknown(m)
}

var xxx_messageInfo_SPlayerLogin proto.InternalMessageInfo

func (m *SPlayerLogin) GetResult() EShinResult {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return EShinResult_LOGIN_SUCCESS
}

func (m *SPlayerLogin) GetPlayerId() uint32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

// 103
type CPlayerInfo struct {
	PlayerId             *uint32  `protobuf:"varint,1,req,name=player_id,json=playerId" json:"player_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CPlayerInfo) Reset()         { *m = CPlayerInfo{} }
func (m *CPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*CPlayerInfo) ProtoMessage()    {}
func (*CPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_c01db11e994b0a2e, []int{4}
}
func (m *CPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CPlayerInfo.Unmarshal(m, b)
}
func (m *CPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CPlayerInfo.Marshal(b, m, deterministic)
}
func (dst *CPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CPlayerInfo.Merge(dst, src)
}
func (m *CPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_CPlayerInfo.Size(m)
}
func (m *CPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CPlayerInfo proto.InternalMessageInfo

func (m *CPlayerInfo) GetPlayerId() uint32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

// 104
type SPlayerInfo struct {
	PlayerId *uint32 `protobuf:"varint,1,req,name=player_id,json=playerId" json:"player_id,omitempty"`
	// 名字
	PlayerName *string `protobuf:"bytes,2,req,name=player_name,json=playerName" json:"player_name,omitempty"`
	// 性别
	Gender *EShinGender `protobuf:"varint,3,req,name=gender,enum=proto.EShinGender" json:"gender,omitempty"`
	// 头像ID
	Avatar *uint32 `protobuf:"varint,4,req,name=avatar" json:"avatar,omitempty"`
	// 金币
	Gold *uint32 `protobuf:"varint,5,req,name=gold" json:"gold,omitempty"`
	// 宝石
	Gems                 *uint32  `protobuf:"varint,6,req,name=gems" json:"gems,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SPlayerInfo) Reset()         { *m = SPlayerInfo{} }
func (m *SPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*SPlayerInfo) ProtoMessage()    {}
func (*SPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_c01db11e994b0a2e, []int{5}
}
func (m *SPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SPlayerInfo.Unmarshal(m, b)
}
func (m *SPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SPlayerInfo.Marshal(b, m, deterministic)
}
func (dst *SPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SPlayerInfo.Merge(dst, src)
}
func (m *SPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_SPlayerInfo.Size(m)
}
func (m *SPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SPlayerInfo proto.InternalMessageInfo

func (m *SPlayerInfo) GetPlayerId() uint32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *SPlayerInfo) GetPlayerName() string {
	if m != nil && m.PlayerName != nil {
		return *m.PlayerName
	}
	return ""
}

func (m *SPlayerInfo) GetGender() EShinGender {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return EShinGender_GENDER_NULL
}

func (m *SPlayerInfo) GetAvatar() uint32 {
	if m != nil && m.Avatar != nil {
		return *m.Avatar
	}
	return 0
}

func (m *SPlayerInfo) GetGold() uint32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func (m *SPlayerInfo) GetGems() uint32 {
	if m != nil && m.Gems != nil {
		return *m.Gems
	}
	return 0
}

// 105 单条玩家属性更新
type CPlayerAttr struct {
	Key                  *EShinPlayerAttr `protobuf:"varint,1,req,name=key,enum=proto.EShinPlayerAttr" json:"key,omitempty"`
	Value                *string          `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CPlayerAttr) Reset()         { *m = CPlayerAttr{} }
func (m *CPlayerAttr) String() string { return proto.CompactTextString(m) }
func (*CPlayerAttr) ProtoMessage()    {}
func (*CPlayerAttr) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_c01db11e994b0a2e, []int{6}
}
func (m *CPlayerAttr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CPlayerAttr.Unmarshal(m, b)
}
func (m *CPlayerAttr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CPlayerAttr.Marshal(b, m, deterministic)
}
func (dst *CPlayerAttr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CPlayerAttr.Merge(dst, src)
}
func (m *CPlayerAttr) XXX_Size() int {
	return xxx_messageInfo_CPlayerAttr.Size(m)
}
func (m *CPlayerAttr) XXX_DiscardUnknown() {
	xxx_messageInfo_CPlayerAttr.DiscardUnknown(m)
}

var xxx_messageInfo_CPlayerAttr proto.InternalMessageInfo

func (m *CPlayerAttr) GetKey() EShinPlayerAttr {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return EShinPlayerAttr_PLAYER_ATTR_NAME
}

func (m *CPlayerAttr) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

// 106 单条玩家属性更新
type SPlayerAttr struct {
	Key                  *EShinPlayerAttr `protobuf:"varint,1,req,name=key,enum=proto.EShinPlayerAttr" json:"key,omitempty"`
	Value                *string          `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SPlayerAttr) Reset()         { *m = SPlayerAttr{} }
func (m *SPlayerAttr) String() string { return proto.CompactTextString(m) }
func (*SPlayerAttr) ProtoMessage()    {}
func (*SPlayerAttr) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_c01db11e994b0a2e, []int{7}
}
func (m *SPlayerAttr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SPlayerAttr.Unmarshal(m, b)
}
func (m *SPlayerAttr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SPlayerAttr.Marshal(b, m, deterministic)
}
func (dst *SPlayerAttr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SPlayerAttr.Merge(dst, src)
}
func (m *SPlayerAttr) XXX_Size() int {
	return xxx_messageInfo_SPlayerAttr.Size(m)
}
func (m *SPlayerAttr) XXX_DiscardUnknown() {
	xxx_messageInfo_SPlayerAttr.DiscardUnknown(m)
}

var xxx_messageInfo_SPlayerAttr proto.InternalMessageInfo

func (m *SPlayerAttr) GetKey() EShinPlayerAttr {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return EShinPlayerAttr_PLAYER_ATTR_NAME
}

func (m *SPlayerAttr) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

// 121
type CServerTime struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CServerTime) Reset()         { *m = CServerTime{} }
func (m *CServerTime) String() string { return proto.CompactTextString(m) }
func (*CServerTime) ProtoMessage()    {}
func (*CServerTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_c01db11e994b0a2e, []int{8}
}
func (m *CServerTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CServerTime.Unmarshal(m, b)
}
func (m *CServerTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CServerTime.Marshal(b, m, deterministic)
}
func (dst *CServerTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CServerTime.Merge(dst, src)
}
func (m *CServerTime) XXX_Size() int {
	return xxx_messageInfo_CServerTime.Size(m)
}
func (m *CServerTime) XXX_DiscardUnknown() {
	xxx_messageInfo_CServerTime.DiscardUnknown(m)
}

var xxx_messageInfo_CServerTime proto.InternalMessageInfo

// 122
type SServerTime struct {
	ServerTime           *uint32  `protobuf:"varint,1,req,name=server_time,json=serverTime" json:"server_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SServerTime) Reset()         { *m = SServerTime{} }
func (m *SServerTime) String() string { return proto.CompactTextString(m) }
func (*SServerTime) ProtoMessage()    {}
func (*SServerTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_c01db11e994b0a2e, []int{9}
}
func (m *SServerTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SServerTime.Unmarshal(m, b)
}
func (m *SServerTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SServerTime.Marshal(b, m, deterministic)
}
func (dst *SServerTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SServerTime.Merge(dst, src)
}
func (m *SServerTime) XXX_Size() int {
	return xxx_messageInfo_SServerTime.Size(m)
}
func (m *SServerTime) XXX_DiscardUnknown() {
	xxx_messageInfo_SServerTime.DiscardUnknown(m)
}

var xxx_messageInfo_SServerTime proto.InternalMessageInfo

func (m *SServerTime) GetServerTime() uint32 {
	if m != nil && m.ServerTime != nil {
		return *m.ServerTime
	}
	return 0
}

// 123
type CGameState struct {
	State                *uint32  `protobuf:"varint,1,req,name=state" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CGameState) Reset()         { *m = CGameState{} }
func (m *CGameState) String() string { return proto.CompactTextString(m) }
func (*CGameState) ProtoMessage()    {}
func (*CGameState) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_c01db11e994b0a2e, []int{10}
}
func (m *CGameState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CGameState.Unmarshal(m, b)
}
func (m *CGameState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CGameState.Marshal(b, m, deterministic)
}
func (dst *CGameState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CGameState.Merge(dst, src)
}
func (m *CGameState) XXX_Size() int {
	return xxx_messageInfo_CGameState.Size(m)
}
func (m *CGameState) XXX_DiscardUnknown() {
	xxx_messageInfo_CGameState.DiscardUnknown(m)
}

var xxx_messageInfo_CGameState proto.InternalMessageInfo

func (m *CGameState) GetState() uint32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

// 124
type SGameState struct {
	State                *uint32  `protobuf:"varint,1,req,name=state" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SGameState) Reset()         { *m = SGameState{} }
func (m *SGameState) String() string { return proto.CompactTextString(m) }
func (*SGameState) ProtoMessage()    {}
func (*SGameState) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_c01db11e994b0a2e, []int{11}
}
func (m *SGameState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SGameState.Unmarshal(m, b)
}
func (m *SGameState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SGameState.Marshal(b, m, deterministic)
}
func (dst *SGameState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SGameState.Merge(dst, src)
}
func (m *SGameState) XXX_Size() int {
	return xxx_messageInfo_SGameState.Size(m)
}
func (m *SGameState) XXX_DiscardUnknown() {
	xxx_messageInfo_SGameState.DiscardUnknown(m)
}

var xxx_messageInfo_SGameState proto.InternalMessageInfo

func (m *SGameState) GetState() uint32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

type PlyerOp struct {
	// [dir.6b|btn.18b|state.8b] dir=63:disable dir<63:enable, btn=1:enable btn=0:disable
	DBS *uint32 `protobuf:"fixed32,1,req,name=d_b_s,json=dBS" json:"d_b_s,omitempty"`
	// [val1.8b|val2.8b|id?.16b]
	V1V2                 *uint32  `protobuf:"varint,2,opt,name=v1_v2,json=v1V2" json:"v1_v2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlyerOp) Reset()         { *m = PlyerOp{} }
func (m *PlyerOp) String() string { return proto.CompactTextString(m) }
func (*PlyerOp) ProtoMessage()    {}
func (*PlyerOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_c01db11e994b0a2e, []int{12}
}
func (m *PlyerOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlyerOp.Unmarshal(m, b)
}
func (m *PlyerOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlyerOp.Marshal(b, m, deterministic)
}
func (dst *PlyerOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlyerOp.Merge(dst, src)
}
func (m *PlyerOp) XXX_Size() int {
	return xxx_messageInfo_PlyerOp.Size(m)
}
func (m *PlyerOp) XXX_DiscardUnknown() {
	xxx_messageInfo_PlyerOp.DiscardUnknown(m)
}

var xxx_messageInfo_PlyerOp proto.InternalMessageInfo

func (m *PlyerOp) GetDBS() uint32 {
	if m != nil && m.DBS != nil {
		return *m.DBS
	}
	return 0
}

func (m *PlyerOp) GetV1V2() uint32 {
	if m != nil && m.V1V2 != nil {
		return *m.V1V2
	}
	return 0
}

// 201 [dir.6b|btn.26b]
// [0-5]                         [6-31]
// dir=63:disable dir<63:enable, btn=1:enable btn=0:disable
type CPlayerFrame struct {
	// [dir.6b|btn.18b|state.8b] dir=63:disable dir<63:enable, btn=1:enable btn=0:disable
	DBS                  []uint32 `protobuf:"fixed32,1,rep,name=d_b_s,json=dBS" json:"d_b_s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CPlayerFrame) Reset()         { *m = CPlayerFrame{} }
func (m *CPlayerFrame) String() string { return proto.CompactTextString(m) }
func (*CPlayerFrame) ProtoMessage()    {}
func (*CPlayerFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_c01db11e994b0a2e, []int{13}
}
func (m *CPlayerFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CPlayerFrame.Unmarshal(m, b)
}
func (m *CPlayerFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CPlayerFrame.Marshal(b, m, deterministic)
}
func (dst *CPlayerFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CPlayerFrame.Merge(dst, src)
}
func (m *CPlayerFrame) XXX_Size() int {
	return xxx_messageInfo_CPlayerFrame.Size(m)
}
func (m *CPlayerFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_CPlayerFrame.DiscardUnknown(m)
}

var xxx_messageInfo_CPlayerFrame proto.InternalMessageInfo

func (m *CPlayerFrame) GetDBS() []uint32 {
	if m != nil {
		return m.DBS
	}
	return nil
}

// unit in scene
type UnitState struct {
	// [id.16b|weapon.16b]
	IdWp *uint32 `protobuf:"fixed32,1,req,name=id_wp,json=idWp" json:"id_wp,omitempty"`
	// [x.16b|y.16b]
	XZ *uint32 `protobuf:"fixed32,2,req,name=x_z,json=xZ" json:"x_z,omitempty"`
	// [dir.6b|state.8b|wear.16b|?.2b]
	// [0-64]  [0-255]
	DSW                  *uint32  `protobuf:"fixed32,3,req,name=d_s_w,json=dSW" json:"d_s_w,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnitState) Reset()         { *m = UnitState{} }
func (m *UnitState) String() string { return proto.CompactTextString(m) }
func (*UnitState) ProtoMessage()    {}
func (*UnitState) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_c01db11e994b0a2e, []int{14}
}
func (m *UnitState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnitState.Unmarshal(m, b)
}
func (m *UnitState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnitState.Marshal(b, m, deterministic)
}
func (dst *UnitState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnitState.Merge(dst, src)
}
func (m *UnitState) XXX_Size() int {
	return xxx_messageInfo_UnitState.Size(m)
}
func (m *UnitState) XXX_DiscardUnknown() {
	xxx_messageInfo_UnitState.DiscardUnknown(m)
}

var xxx_messageInfo_UnitState proto.InternalMessageInfo

func (m *UnitState) GetIdWp() uint32 {
	if m != nil && m.IdWp != nil {
		return *m.IdWp
	}
	return 0
}

func (m *UnitState) GetXZ() uint32 {
	if m != nil && m.XZ != nil {
		return *m.XZ
	}
	return 0
}

func (m *UnitState) GetDSW() uint32 {
	if m != nil && m.DSW != nil {
		return *m.DSW
	}
	return 0
}

type OpResult struct {
	// [op.16b|id.16b]
	OpId *uint32 `protobuf:"fixed32,1,req,name=op_id,json=opId" json:"op_id,omitempty"`
	// [v1.8b|v2.8b|?.16b]
	V1V2                 *uint32  `protobuf:"fixed32,2,opt,name=v1_v2,json=v1V2" json:"v1_v2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpResult) Reset()         { *m = OpResult{} }
func (m *OpResult) String() string { return proto.CompactTextString(m) }
func (*OpResult) ProtoMessage()    {}
func (*OpResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_c01db11e994b0a2e, []int{15}
}
func (m *OpResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpResult.Unmarshal(m, b)
}
func (m *OpResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpResult.Marshal(b, m, deterministic)
}
func (dst *OpResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpResult.Merge(dst, src)
}
func (m *OpResult) XXX_Size() int {
	return xxx_messageInfo_OpResult.Size(m)
}
func (m *OpResult) XXX_DiscardUnknown() {
	xxx_messageInfo_OpResult.DiscardUnknown(m)
}

var xxx_messageInfo_OpResult proto.InternalMessageInfo

func (m *OpResult) GetOpId() uint32 {
	if m != nil && m.OpId != nil {
		return *m.OpId
	}
	return 0
}

func (m *OpResult) GetV1V2() uint32 {
	if m != nil && m.V1V2 != nil {
		return *m.V1V2
	}
	return 0
}

// 202
type SPlayerFrame struct {
	Units                []*UnitState `protobuf:"bytes,1,rep,name=units" json:"units,omitempty"`
	Ops                  []*OpResult  `protobuf:"bytes,2,rep,name=ops" json:"ops,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SPlayerFrame) Reset()         { *m = SPlayerFrame{} }
func (m *SPlayerFrame) String() string { return proto.CompactTextString(m) }
func (*SPlayerFrame) ProtoMessage()    {}
func (*SPlayerFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_c01db11e994b0a2e, []int{16}
}
func (m *SPlayerFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SPlayerFrame.Unmarshal(m, b)
}
func (m *SPlayerFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SPlayerFrame.Marshal(b, m, deterministic)
}
func (dst *SPlayerFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SPlayerFrame.Merge(dst, src)
}
func (m *SPlayerFrame) XXX_Size() int {
	return xxx_messageInfo_SPlayerFrame.Size(m)
}
func (m *SPlayerFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_SPlayerFrame.DiscardUnknown(m)
}

var xxx_messageInfo_SPlayerFrame proto.InternalMessageInfo

func (m *SPlayerFrame) GetUnits() []*UnitState {
	if m != nil {
		return m.Units
	}
	return nil
}

func (m *SPlayerFrame) GetOps() []*OpResult {
	if m != nil {
		return m.Ops
	}
	return nil
}

func init() {
	proto.RegisterType((*C2SLogin)(nil), "proto.c2s_login")
	proto.RegisterType((*S2CLogin)(nil), "proto.s2c_login")
	proto.RegisterType((*CPlayerLogin)(nil), "proto.c_player_login")
	proto.RegisterType((*SPlayerLogin)(nil), "proto.s_player_login")
	proto.RegisterType((*CPlayerInfo)(nil), "proto.c_player_info")
	proto.RegisterType((*SPlayerInfo)(nil), "proto.s_player_info")
	proto.RegisterType((*CPlayerAttr)(nil), "proto.c_player_attr")
	proto.RegisterType((*SPlayerAttr)(nil), "proto.s_player_attr")
	proto.RegisterType((*CServerTime)(nil), "proto.c_server_time")
	proto.RegisterType((*SServerTime)(nil), "proto.s_server_time")
	proto.RegisterType((*CGameState)(nil), "proto.c_game_state")
	proto.RegisterType((*SGameState)(nil), "proto.s_game_state")
	proto.RegisterType((*PlyerOp)(nil), "proto.plyer_op")
	proto.RegisterType((*CPlayerFrame)(nil), "proto.c_player_frame")
	proto.RegisterType((*UnitState)(nil), "proto.unit_state")
	proto.RegisterType((*OpResult)(nil), "proto.op_result")
	proto.RegisterType((*SPlayerFrame)(nil), "proto.s_player_frame")
	proto.RegisterEnum("proto.EShinResult", EShinResult_name, EShinResult_value)
	proto.RegisterEnum("proto.EShinGender", EShinGender_name, EShinGender_value)
	proto.RegisterEnum("proto.EShinPlayerAttr", EShinPlayerAttr_name, EShinPlayerAttr_value)
	proto.RegisterEnum("proto.EShinOnline", EShinOnline_name, EShinOnline_value)
}

func init() { proto.RegisterFile("shin.proto", fileDescriptor_shin_c01db11e994b0a2e) }

var fileDescriptor_shin_c01db11e994b0a2e = []byte{
	// 748 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x5d, 0x8f, 0xdb, 0x44,
	0x14, 0x6d, 0xec, 0x38, 0xd9, 0xdc, 0x6c, 0x92, 0xe9, 0x6c, 0x58, 0x5c, 0x3e, 0x44, 0x65, 0x15,
	0x81, 0x96, 0xaa, 0xa2, 0x41, 0xbc, 0xf0, 0x66, 0x12, 0x67, 0xd7, 0x92, 0xe3, 0xac, 0xc6, 0x69,
	0x2a, 0x40, 0x68, 0x64, 0xe2, 0x49, 0xb0, 0x48, 0x6c, 0xcb, 0xe3, 0x4d, 0x5b, 0xfe, 0x1a, 0x2f,
	0xfc, 0x34, 0x34, 0x1f, 0xd9, 0x3a, 0x59, 0x24, 0x78, 0xe8, 0x93, 0xe7, 0x9e, 0x7b, 0xee, 0xb9,
	0x67, 0xee, 0x5c, 0x03, 0xf0, 0xdf, 0xd3, 0xec, 0x45, 0x51, 0xe6, 0x55, 0x8e, 0x2d, 0xf9, 0x71,
	0xbe, 0x84, 0xce, 0x6a, 0xc4, 0xe9, 0x36, 0xdf, 0xa4, 0x19, 0xb6, 0xa1, 0x1d, 0xaf, 0x56, 0x59,
	0xbc, 0x63, 0x76, 0xe3, 0xa9, 0xf1, 0x75, 0x87, 0x1c, 0x42, 0xe7, 0x73, 0xe8, 0xf0, 0xd1, 0x4a,
	0xd3, 0x10, 0x98, 0x25, 0xab, 0x24, 0xc5, 0x22, 0xe2, 0xe8, 0xfc, 0x00, 0xfd, 0x15, 0x2d, 0xb6,
	0xf1, 0x3b, 0x56, 0xbe, 0x97, 0xe2, 0x8c, 0xf3, 0x34, 0xcf, 0x0e, 0x52, 0x3a, 0xc4, 0x7d, 0x30,
	0x8a, 0xb5, 0x6d, 0x48, 0xd0, 0x28, 0xd6, 0xce, 0x2f, 0xd0, 0xe7, 0xc7, 0xb5, 0xcf, 0xa1, 0x55,
	0x32, 0x7e, 0xb7, 0x55, 0x2d, 0xfa, 0xa3, 0xa1, 0xb2, 0xfc, 0x82, 0x51, 0xe1, 0x9f, 0xaa, 0x1c,
	0xd1, 0x1c, 0xfc, 0x29, 0x74, 0x74, 0x75, 0x9a, 0x48, 0xd9, 0x1e, 0x39, 0x53, 0x80, 0x9f, 0x38,
	0xcf, 0xa1, 0x77, 0x6f, 0x2c, 0xcd, 0xd6, 0xf9, 0x31, 0xbb, 0x71, 0xc2, 0xfe, 0xab, 0x01, 0x3d,
	0xfe, 0xbf, 0xe9, 0xf8, 0x0b, 0xe8, 0xea, 0xa4, 0x1c, 0x99, 0xba, 0x12, 0x28, 0x28, 0x8c, 0x77,
	0x4c, 0x5c, 0x64, 0xc3, 0xb2, 0x84, 0x95, 0xb6, 0xf9, 0x6f, 0x17, 0x51, 0x39, 0xa2, 0x39, 0xf8,
	0x12, 0x5a, 0xf1, 0x3e, 0xae, 0xe2, 0xd2, 0x6e, 0xca, 0x46, 0x3a, 0xc2, 0x18, 0x9a, 0x9b, 0x7c,
	0x9b, 0xd8, 0x96, 0x44, 0xe5, 0x59, 0x62, 0x6c, 0xc7, 0xed, 0x96, 0xc6, 0xd8, 0x8e, 0x3b, 0xa4,
	0x76, 0xd7, 0xb8, 0xaa, 0x4a, 0xfc, 0x0d, 0x98, 0x7f, 0xb0, 0x77, 0x7a, 0x88, 0x4f, 0x8e, 0x7b,
	0xd7, 0x78, 0x44, 0xb0, 0xf0, 0x10, 0xac, 0x7d, 0xbc, 0xbd, 0x3b, 0x5c, 0x43, 0x05, 0x42, 0x93,
	0x7f, 0x68, 0xcd, 0x81, 0xf0, 0xc9, 0x59, 0xb9, 0x67, 0x25, 0xad, 0xd2, 0x1d, 0x73, 0xbe, 0x15,
	0x4d, 0x6a, 0x80, 0x18, 0x6c, 0x2d, 0xd4, 0x73, 0x07, 0x05, 0x2d, 0x44, 0xc5, 0x33, 0x38, 0x5f,
	0xd1, 0x4d, 0xbc, 0x63, 0x94, 0x57, 0x71, 0xc5, 0x44, 0x23, 0x79, 0xd0, 0x54, 0x15, 0x08, 0x16,
	0xff, 0x6f, 0xd6, 0x77, 0x70, 0x56, 0x6c, 0x85, 0xef, 0xbc, 0xc0, 0x18, 0xac, 0x84, 0xfe, 0x46,
	0xb9, 0x64, 0xb4, 0x89, 0x99, 0xfc, 0x18, 0xe1, 0x0b, 0xb0, 0xf6, 0x2f, 0xe9, 0x7e, 0x64, 0x1b,
	0x4f, 0x1b, 0x62, 0xd6, 0xfb, 0x97, 0xcb, 0x91, 0xf3, 0xac, 0xb6, 0xf0, 0xeb, 0x52, 0xbc, 0x75,
	0xad, 0xd4, 0xd4, 0xa5, 0xce, 0x14, 0xe0, 0x2e, 0x4b, 0x2b, 0xdd, 0xfe, 0x02, 0xac, 0x34, 0xa1,
	0x6f, 0x0a, 0x2d, 0xde, 0x4c, 0x93, 0xd7, 0x05, 0x1e, 0x80, 0xf9, 0x96, 0xfe, 0x29, 0x07, 0xd4,
	0x26, 0xc6, 0xdb, 0x9f, 0x95, 0x0e, 0xa7, 0x6f, 0xe4, 0xca, 0x08, 0x9d, 0xe8, 0xb5, 0xf3, 0x3d,
	0x74, 0xf2, 0x42, 0xef, 0xbd, 0x90, 0xc9, 0x8b, 0xc3, 0x3a, 0xb6, 0x49, 0x33, 0x2f, 0xfc, 0xe4,
	0xd8, 0x64, 0x5b, 0x9b, 0xfc, 0xb5, 0xf6, 0x67, 0x29, 0x93, 0x5f, 0x81, 0x25, 0x0c, 0x29, 0x93,
	0xdd, 0xd1, 0x63, 0xfd, 0x7e, 0xef, 0x4d, 0x12, 0x95, 0xc7, 0x0e, 0x98, 0x79, 0xc1, 0x6d, 0x43,
	0xd2, 0x90, 0xa6, 0xdd, 0x7b, 0x20, 0x22, 0x79, 0x35, 0x82, 0xde, 0xd1, 0x1f, 0x89, 0x1f, 0x43,
	0x2f, 0x98, 0x5f, 0xfb, 0x21, 0x8d, 0x5e, 0x8d, 0xc7, 0x5e, 0x14, 0xa1, 0x47, 0xb8, 0x0f, 0xa0,
	0xa0, 0xa9, 0xeb, 0x07, 0xa8, 0x71, 0x35, 0xb9, 0xaf, 0xd1, 0x4b, 0x3f, 0x80, 0xee, 0xb5, 0x17,
	0x4e, 0x3c, 0x42, 0xc3, 0x57, 0x41, 0x80, 0x1e, 0xd5, 0x80, 0x99, 0x1b, 0x78, 0xa8, 0x21, 0x54,
	0x35, 0x30, 0xf5, 0x66, 0x42, 0xc5, 0xb8, 0xfa, 0xdb, 0x00, 0xfc, 0x70, 0xe7, 0xf0, 0x10, 0xd0,
	0x6d, 0xe0, 0xfe, 0xe4, 0x11, 0xea, 0x2e, 0x16, 0x84, 0x86, 0xee, 0xcc, 0x43, 0x26, 0xbe, 0x04,
	0x5c, 0x47, 0x95, 0x16, 0x6a, 0x9e, 0xe2, 0xee, 0xd2, 0x5d, 0xb8, 0x04, 0x59, 0xa7, 0x2a, 0xd7,
	0xf3, 0x60, 0x82, 0x5a, 0x0f, 0x50, 0x6f, 0x16, 0xa1, 0x36, 0xc6, 0xd0, 0xaf, 0xa3, 0xb7, 0x37,
	0xe8, 0x0c, 0x7f, 0x06, 0xf6, 0x11, 0xb6, 0xbc, 0xa5, 0x13, 0x7f, 0xe9, 0x47, 0xfe, 0x3c, 0x44,
	0x1d, 0x6c, 0xc3, 0xf0, 0x34, 0x1b, 0x89, 0xbe, 0x80, 0x9f, 0xc0, 0x47, 0x0f, 0x32, 0xe3, 0x39,
	0xf1, 0x50, 0xf7, 0x54, 0x72, 0x7c, 0xe3, 0x2e, 0x68, 0xe4, 0x45, 0x52, 0xf2, 0x1c, 0x7f, 0x02,
	0x97, 0xc7, 0x26, 0xe8, 0x78, 0x1e, 0x4e, 0x7d, 0x32, 0x43, 0x7d, 0xfc, 0x31, 0x5c, 0x9c, 0xe4,
	0x02, 0x3f, 0x5a, 0xa0, 0x41, 0xed, 0xf1, 0xf2, 0x6c, 0x9b, 0x66, 0x0c, 0x23, 0x38, 0x8f, 0x6e,
	0xfc, 0x90, 0xce, 0xa7, 0xd3, 0xc0, 0x0f, 0x3d, 0xf5, 0x12, 0x0a, 0x09, 0x25, 0xd0, 0xf8, 0x27,
	0x00, 0x00, 0xff, 0xff, 0xd1, 0x42, 0x4b, 0x56, 0x3f, 0x06, 0x00, 0x00,
}
