// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shin.proto

package mproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 全局枚举
type ECode int32

const (
	ECode_ok   ECode = 0
	ECode_fail ECode = 1
)

var ECode_name = map[int32]string{
	0: "ok",
	1: "fail",
}
var ECode_value = map[string]int32{
	"ok":   0,
	"fail": 1,
}

func (x ECode) Enum() *ECode {
	p := new(ECode)
	*p = x
	return p
}
func (x ECode) String() string {
	return proto.EnumName(ECode_name, int32(x))
}
func (x *ECode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ECode_value, data, "ECode")
	if err != nil {
		return err
	}
	*x = ECode(value)
	return nil
}
func (ECode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_shin_e8ba8674d9e30b63, []int{0}
}

type EShinGender int32

const (
	EShinGender_GENDER_NULL   EShinGender = 0
	EShinGender_GENDER_MALE   EShinGender = 1
	EShinGender_GENDER_FEMAIL EShinGender = 2
)

var EShinGender_name = map[int32]string{
	0: "GENDER_NULL",
	1: "GENDER_MALE",
	2: "GENDER_FEMAIL",
}
var EShinGender_value = map[string]int32{
	"GENDER_NULL":   0,
	"GENDER_MALE":   1,
	"GENDER_FEMAIL": 2,
}

func (x EShinGender) Enum() *EShinGender {
	p := new(EShinGender)
	*p = x
	return p
}
func (x EShinGender) String() string {
	return proto.EnumName(EShinGender_name, int32(x))
}
func (x *EShinGender) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EShinGender_value, data, "EShinGender")
	if err != nil {
		return err
	}
	*x = EShinGender(value)
	return nil
}
func (EShinGender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_shin_e8ba8674d9e30b63, []int{1}
}

type EBattleObjType int32

const (
	EBattleObjType_OBJ_UNIT   EBattleObjType = 0
	EBattleObjType_OBJ_WEAPON EBattleObjType = 1
	EBattleObjType_OBJ_ITEM   EBattleObjType = 2
	EBattleObjType_OBJ_BULLET EBattleObjType = 3
)

var EBattleObjType_name = map[int32]string{
	0: "OBJ_UNIT",
	1: "OBJ_WEAPON",
	2: "OBJ_ITEM",
	3: "OBJ_BULLET",
}
var EBattleObjType_value = map[string]int32{
	"OBJ_UNIT":   0,
	"OBJ_WEAPON": 1,
	"OBJ_ITEM":   2,
	"OBJ_BULLET": 3,
}

func (x EBattleObjType) Enum() *EBattleObjType {
	p := new(EBattleObjType)
	*p = x
	return p
}
func (x EBattleObjType) String() string {
	return proto.EnumName(EBattleObjType_name, int32(x))
}
func (x *EBattleObjType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EBattleObjType_value, data, "EBattleObjType")
	if err != nil {
		return err
	}
	*x = EBattleObjType(value)
	return nil
}
func (EBattleObjType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_shin_e8ba8674d9e30b63, []int{2}
}

// ------------------玩家登陆相关(模块10)-----------------
// 1001
type CPlayerLogin struct {
	Token                *string  `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
	Pf                   *string  `protobuf:"bytes,2,req,name=pf" json:"pf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CPlayerLogin) Reset()         { *m = CPlayerLogin{} }
func (m *CPlayerLogin) String() string { return proto.CompactTextString(m) }
func (*CPlayerLogin) ProtoMessage()    {}
func (*CPlayerLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_e8ba8674d9e30b63, []int{0}
}
func (m *CPlayerLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CPlayerLogin.Unmarshal(m, b)
}
func (m *CPlayerLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CPlayerLogin.Marshal(b, m, deterministic)
}
func (dst *CPlayerLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CPlayerLogin.Merge(dst, src)
}
func (m *CPlayerLogin) XXX_Size() int {
	return xxx_messageInfo_CPlayerLogin.Size(m)
}
func (m *CPlayerLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_CPlayerLogin.DiscardUnknown(m)
}

var xxx_messageInfo_CPlayerLogin proto.InternalMessageInfo

func (m *CPlayerLogin) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *CPlayerLogin) GetPf() string {
	if m != nil && m.Pf != nil {
		return *m.Pf
	}
	return ""
}

// 1002
type SPlayerLogin struct {
	Code                 *ECode   `protobuf:"varint,1,req,name=code,enum=mproto.ECode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SPlayerLogin) Reset()         { *m = SPlayerLogin{} }
func (m *SPlayerLogin) String() string { return proto.CompactTextString(m) }
func (*SPlayerLogin) ProtoMessage()    {}
func (*SPlayerLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_e8ba8674d9e30b63, []int{1}
}
func (m *SPlayerLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SPlayerLogin.Unmarshal(m, b)
}
func (m *SPlayerLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SPlayerLogin.Marshal(b, m, deterministic)
}
func (dst *SPlayerLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SPlayerLogin.Merge(dst, src)
}
func (m *SPlayerLogin) XXX_Size() int {
	return xxx_messageInfo_SPlayerLogin.Size(m)
}
func (m *SPlayerLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_SPlayerLogin.DiscardUnknown(m)
}

var xxx_messageInfo_SPlayerLogin proto.InternalMessageInfo

func (m *SPlayerLogin) GetCode() ECode {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ECode_ok
}

// 1003
type CServerTime struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CServerTime) Reset()         { *m = CServerTime{} }
func (m *CServerTime) String() string { return proto.CompactTextString(m) }
func (*CServerTime) ProtoMessage()    {}
func (*CServerTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_e8ba8674d9e30b63, []int{2}
}
func (m *CServerTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CServerTime.Unmarshal(m, b)
}
func (m *CServerTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CServerTime.Marshal(b, m, deterministic)
}
func (dst *CServerTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CServerTime.Merge(dst, src)
}
func (m *CServerTime) XXX_Size() int {
	return xxx_messageInfo_CServerTime.Size(m)
}
func (m *CServerTime) XXX_DiscardUnknown() {
	xxx_messageInfo_CServerTime.DiscardUnknown(m)
}

var xxx_messageInfo_CServerTime proto.InternalMessageInfo

// 1004
type SServerTime struct {
	ServerTime           *uint64  `protobuf:"varint,1,req,name=server_time,json=serverTime" json:"server_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SServerTime) Reset()         { *m = SServerTime{} }
func (m *SServerTime) String() string { return proto.CompactTextString(m) }
func (*SServerTime) ProtoMessage()    {}
func (*SServerTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_e8ba8674d9e30b63, []int{3}
}
func (m *SServerTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SServerTime.Unmarshal(m, b)
}
func (m *SServerTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SServerTime.Marshal(b, m, deterministic)
}
func (dst *SServerTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SServerTime.Merge(dst, src)
}
func (m *SServerTime) XXX_Size() int {
	return xxx_messageInfo_SServerTime.Size(m)
}
func (m *SServerTime) XXX_DiscardUnknown() {
	xxx_messageInfo_SServerTime.DiscardUnknown(m)
}

var xxx_messageInfo_SServerTime proto.InternalMessageInfo

func (m *SServerTime) GetServerTime() uint64 {
	if m != nil && m.ServerTime != nil {
		return *m.ServerTime
	}
	return 0
}

// -----------------游戏大厅相关(模块11)----------------
// 1101 进入大厅
type CLobbyEnter struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CLobbyEnter) Reset()         { *m = CLobbyEnter{} }
func (m *CLobbyEnter) String() string { return proto.CompactTextString(m) }
func (*CLobbyEnter) ProtoMessage()    {}
func (*CLobbyEnter) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_e8ba8674d9e30b63, []int{4}
}
func (m *CLobbyEnter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CLobbyEnter.Unmarshal(m, b)
}
func (m *CLobbyEnter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CLobbyEnter.Marshal(b, m, deterministic)
}
func (dst *CLobbyEnter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CLobbyEnter.Merge(dst, src)
}
func (m *CLobbyEnter) XXX_Size() int {
	return xxx_messageInfo_CLobbyEnter.Size(m)
}
func (m *CLobbyEnter) XXX_DiscardUnknown() {
	xxx_messageInfo_CLobbyEnter.DiscardUnknown(m)
}

var xxx_messageInfo_CLobbyEnter proto.InternalMessageInfo

// 1102 进入大厅
type SLobbyEnter struct {
	RoomId               *int32   `protobuf:"varint,1,req,name=room_id,json=roomId" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SLobbyEnter) Reset()         { *m = SLobbyEnter{} }
func (m *SLobbyEnter) String() string { return proto.CompactTextString(m) }
func (*SLobbyEnter) ProtoMessage()    {}
func (*SLobbyEnter) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_e8ba8674d9e30b63, []int{5}
}
func (m *SLobbyEnter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SLobbyEnter.Unmarshal(m, b)
}
func (m *SLobbyEnter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SLobbyEnter.Marshal(b, m, deterministic)
}
func (dst *SLobbyEnter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SLobbyEnter.Merge(dst, src)
}
func (m *SLobbyEnter) XXX_Size() int {
	return xxx_messageInfo_SLobbyEnter.Size(m)
}
func (m *SLobbyEnter) XXX_DiscardUnknown() {
	xxx_messageInfo_SLobbyEnter.DiscardUnknown(m)
}

var xxx_messageInfo_SLobbyEnter proto.InternalMessageInfo

func (m *SLobbyEnter) GetRoomId() int32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

// 1103 开始匹配新的一局游戏
type CLobbyMutch struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CLobbyMutch) Reset()         { *m = CLobbyMutch{} }
func (m *CLobbyMutch) String() string { return proto.CompactTextString(m) }
func (*CLobbyMutch) ProtoMessage()    {}
func (*CLobbyMutch) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_e8ba8674d9e30b63, []int{6}
}
func (m *CLobbyMutch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CLobbyMutch.Unmarshal(m, b)
}
func (m *CLobbyMutch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CLobbyMutch.Marshal(b, m, deterministic)
}
func (dst *CLobbyMutch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CLobbyMutch.Merge(dst, src)
}
func (m *CLobbyMutch) XXX_Size() int {
	return xxx_messageInfo_CLobbyMutch.Size(m)
}
func (m *CLobbyMutch) XXX_DiscardUnknown() {
	xxx_messageInfo_CLobbyMutch.DiscardUnknown(m)
}

var xxx_messageInfo_CLobbyMutch proto.InternalMessageInfo

// 1104 开始匹配新的一局游戏
type SLobbyMutch struct {
	Result               *uint32  `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SLobbyMutch) Reset()         { *m = SLobbyMutch{} }
func (m *SLobbyMutch) String() string { return proto.CompactTextString(m) }
func (*SLobbyMutch) ProtoMessage()    {}
func (*SLobbyMutch) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_e8ba8674d9e30b63, []int{7}
}
func (m *SLobbyMutch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SLobbyMutch.Unmarshal(m, b)
}
func (m *SLobbyMutch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SLobbyMutch.Marshal(b, m, deterministic)
}
func (dst *SLobbyMutch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SLobbyMutch.Merge(dst, src)
}
func (m *SLobbyMutch) XXX_Size() int {
	return xxx_messageInfo_SLobbyMutch.Size(m)
}
func (m *SLobbyMutch) XXX_DiscardUnknown() {
	xxx_messageInfo_SLobbyMutch.DiscardUnknown(m)
}

var xxx_messageInfo_SLobbyMutch proto.InternalMessageInfo

func (m *SLobbyMutch) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// 1105 取消匹配新的一局游戏
type CLobbyCancel struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CLobbyCancel) Reset()         { *m = CLobbyCancel{} }
func (m *CLobbyCancel) String() string { return proto.CompactTextString(m) }
func (*CLobbyCancel) ProtoMessage()    {}
func (*CLobbyCancel) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_e8ba8674d9e30b63, []int{8}
}
func (m *CLobbyCancel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CLobbyCancel.Unmarshal(m, b)
}
func (m *CLobbyCancel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CLobbyCancel.Marshal(b, m, deterministic)
}
func (dst *CLobbyCancel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CLobbyCancel.Merge(dst, src)
}
func (m *CLobbyCancel) XXX_Size() int {
	return xxx_messageInfo_CLobbyCancel.Size(m)
}
func (m *CLobbyCancel) XXX_DiscardUnknown() {
	xxx_messageInfo_CLobbyCancel.DiscardUnknown(m)
}

var xxx_messageInfo_CLobbyCancel proto.InternalMessageInfo

// 1106 取消匹配新的一局游戏
type SLobbyCancel struct {
	Result               *uint32  `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SLobbyCancel) Reset()         { *m = SLobbyCancel{} }
func (m *SLobbyCancel) String() string { return proto.CompactTextString(m) }
func (*SLobbyCancel) ProtoMessage()    {}
func (*SLobbyCancel) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_e8ba8674d9e30b63, []int{9}
}
func (m *SLobbyCancel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SLobbyCancel.Unmarshal(m, b)
}
func (m *SLobbyCancel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SLobbyCancel.Marshal(b, m, deterministic)
}
func (dst *SLobbyCancel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SLobbyCancel.Merge(dst, src)
}
func (m *SLobbyCancel) XXX_Size() int {
	return xxx_messageInfo_SLobbyCancel.Size(m)
}
func (m *SLobbyCancel) XXX_DiscardUnknown() {
	xxx_messageInfo_SLobbyCancel.DiscardUnknown(m)
}

var xxx_messageInfo_SLobbyCancel proto.InternalMessageInfo

func (m *SLobbyCancel) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// ----------------玩家信息相关(模块20)---------------
// 2001
type CPlayerInfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CPlayerInfo) Reset()         { *m = CPlayerInfo{} }
func (m *CPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*CPlayerInfo) ProtoMessage()    {}
func (*CPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_e8ba8674d9e30b63, []int{10}
}
func (m *CPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CPlayerInfo.Unmarshal(m, b)
}
func (m *CPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CPlayerInfo.Marshal(b, m, deterministic)
}
func (dst *CPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CPlayerInfo.Merge(dst, src)
}
func (m *CPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_CPlayerInfo.Size(m)
}
func (m *CPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CPlayerInfo proto.InternalMessageInfo

// 2002
type SPlayerInfo struct {
	PlayerId             *uint32      `protobuf:"varint,1,req,name=player_id,json=playerId" json:"player_id,omitempty"`
	PlayerName           *string      `protobuf:"bytes,2,req,name=player_name,json=playerName" json:"player_name,omitempty"`
	Gender               *EShinGender `protobuf:"varint,3,req,name=gender,enum=mproto.EShinGender" json:"gender,omitempty"`
	Avatar               *uint32      `protobuf:"varint,4,req,name=avatar" json:"avatar,omitempty"`
	Gold                 *uint32      `protobuf:"varint,5,opt,name=gold,def=0" json:"gold,omitempty"`
	Gems                 *uint32      `protobuf:"varint,6,opt,name=gems,def=0" json:"gems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SPlayerInfo) Reset()         { *m = SPlayerInfo{} }
func (m *SPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*SPlayerInfo) ProtoMessage()    {}
func (*SPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_e8ba8674d9e30b63, []int{11}
}
func (m *SPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SPlayerInfo.Unmarshal(m, b)
}
func (m *SPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SPlayerInfo.Marshal(b, m, deterministic)
}
func (dst *SPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SPlayerInfo.Merge(dst, src)
}
func (m *SPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_SPlayerInfo.Size(m)
}
func (m *SPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SPlayerInfo proto.InternalMessageInfo

const Default_SPlayerInfo_Gold uint32 = 0
const Default_SPlayerInfo_Gems uint32 = 0

func (m *SPlayerInfo) GetPlayerId() uint32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *SPlayerInfo) GetPlayerName() string {
	if m != nil && m.PlayerName != nil {
		return *m.PlayerName
	}
	return ""
}

func (m *SPlayerInfo) GetGender() EShinGender {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return EShinGender_GENDER_NULL
}

func (m *SPlayerInfo) GetAvatar() uint32 {
	if m != nil && m.Avatar != nil {
		return *m.Avatar
	}
	return 0
}

func (m *SPlayerInfo) GetGold() uint32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return Default_SPlayerInfo_Gold
}

func (m *SPlayerInfo) GetGems() uint32 {
	if m != nil && m.Gems != nil {
		return *m.Gems
	}
	return Default_SPlayerInfo_Gems
}

type CPlayerFrame struct {
	Op                   []byte   `protobuf:"bytes,1,req,name=op" json:"op,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CPlayerFrame) Reset()         { *m = CPlayerFrame{} }
func (m *CPlayerFrame) String() string { return proto.CompactTextString(m) }
func (*CPlayerFrame) ProtoMessage()    {}
func (*CPlayerFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_e8ba8674d9e30b63, []int{12}
}
func (m *CPlayerFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CPlayerFrame.Unmarshal(m, b)
}
func (m *CPlayerFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CPlayerFrame.Marshal(b, m, deterministic)
}
func (dst *CPlayerFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CPlayerFrame.Merge(dst, src)
}
func (m *CPlayerFrame) XXX_Size() int {
	return xxx_messageInfo_CPlayerFrame.Size(m)
}
func (m *CPlayerFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_CPlayerFrame.DiscardUnknown(m)
}

var xxx_messageInfo_CPlayerFrame proto.InternalMessageInfo

func (m *CPlayerFrame) GetOp() []byte {
	if m != nil {
		return m.Op
	}
	return nil
}

// 3002
type SPlayerFrame struct {
	// 玩家属性[id.8b|dir.8b|x.16b|y.16b]
	Units []byte `protobuf:"bytes,1,opt,name=units" json:"units,omitempty"`
	// 玩家附加属性[id.8b|weapon.8b|wear.8b|shield.8b|hp.10b|hp_max.10b|itemcount.8b|预留.4b]
	ExtraUnits []byte `protobuf:"bytes,2,opt,name=extra_units,json=extraUnits" json:"extra_units,omitempty"`
	// 物品[id.14|owner.8b|baseid.8b|state.2b|x.16b|y.16b]
	// state==1销毁物品  owner > 0说明被人捡起要在场景里消失 owner == 0 物品要重新回到场景中显示出来
	Items []byte `protobuf:"bytes,3,opt,name=items" json:"items,omitempty"`
	// 武器[id.14|owner.8b|baseid.8b|state.2b|x.16b|y.16b]b
	// state==1销毁武器  owner > 0说明被人捡起要在场景里消失 owner == 0 武器要重新回到场景中显示出来
	// baseid 是预留的，不要处理
	Weapons []byte `protobuf:"bytes,4,opt,name=weapons" json:"weapons,omitempty"`
	// 子弹[id.14|dir.8b|add_speed.10b|x.16b|y.16b|weaponType.8b|add_range.8b]
	Bullets []byte `protobuf:"bytes,5,opt,name=bullets" json:"bullets,omitempty"`
	// 操作返回 [op.8b|id.14b|type.2b|val.8b]
	// [开火|子弹id|子弹|子弹数量]
	// [换枪|最新装备的枪的唯一id|武器|0]
	// [拾取|枪唯一id(物品类型id)|武器(物品)|枪的子弹数(物品数)]
	// 属性返回
	// 能量属性返回[op.8|mp_max.12b|mp.12b]
	Ops                  []byte   `protobuf:"bytes,8,opt,name=ops" json:"ops,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SPlayerFrame) Reset()         { *m = SPlayerFrame{} }
func (m *SPlayerFrame) String() string { return proto.CompactTextString(m) }
func (*SPlayerFrame) ProtoMessage()    {}
func (*SPlayerFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_e8ba8674d9e30b63, []int{13}
}
func (m *SPlayerFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SPlayerFrame.Unmarshal(m, b)
}
func (m *SPlayerFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SPlayerFrame.Marshal(b, m, deterministic)
}
func (dst *SPlayerFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SPlayerFrame.Merge(dst, src)
}
func (m *SPlayerFrame) XXX_Size() int {
	return xxx_messageInfo_SPlayerFrame.Size(m)
}
func (m *SPlayerFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_SPlayerFrame.DiscardUnknown(m)
}

var xxx_messageInfo_SPlayerFrame proto.InternalMessageInfo

func (m *SPlayerFrame) GetUnits() []byte {
	if m != nil {
		return m.Units
	}
	return nil
}

func (m *SPlayerFrame) GetExtraUnits() []byte {
	if m != nil {
		return m.ExtraUnits
	}
	return nil
}

func (m *SPlayerFrame) GetItems() []byte {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *SPlayerFrame) GetWeapons() []byte {
	if m != nil {
		return m.Weapons
	}
	return nil
}

func (m *SPlayerFrame) GetBullets() []byte {
	if m != nil {
		return m.Bullets
	}
	return nil
}

func (m *SPlayerFrame) GetOps() []byte {
	if m != nil {
		return m.Ops
	}
	return nil
}

// 获取场景信息
// 3003
type CBattleStart struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CBattleStart) Reset()         { *m = CBattleStart{} }
func (m *CBattleStart) String() string { return proto.CompactTextString(m) }
func (*CBattleStart) ProtoMessage()    {}
func (*CBattleStart) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_e8ba8674d9e30b63, []int{14}
}
func (m *CBattleStart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CBattleStart.Unmarshal(m, b)
}
func (m *CBattleStart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CBattleStart.Marshal(b, m, deterministic)
}
func (dst *CBattleStart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CBattleStart.Merge(dst, src)
}
func (m *CBattleStart) XXX_Size() int {
	return xxx_messageInfo_CBattleStart.Size(m)
}
func (m *CBattleStart) XXX_DiscardUnknown() {
	xxx_messageInfo_CBattleStart.DiscardUnknown(m)
}

var xxx_messageInfo_CBattleStart proto.InternalMessageInfo

// 3004
type SBattleInfo struct {
	Bid                  *int32        `protobuf:"varint,1,req,name=bid" json:"bid,omitempty"`
	List                 []*PBattleObj `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
	IsStart              *int32        `protobuf:"varint,3,req,name=is_start,json=isStart" json:"is_start,omitempty"`
	OwnWeapons           []*PWeapon    `protobuf:"bytes,4,rep,name=own_weapons,json=ownWeapons" json:"own_weapons,omitempty"`
	OwnItems             []*PItem      `protobuf:"bytes,5,rep,name=own_items,json=ownItems" json:"own_items,omitempty"`
	TimeStart            *uint32       `protobuf:"varint,7,opt,name=time_start,json=timeStart" json:"time_start,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SBattleInfo) Reset()         { *m = SBattleInfo{} }
func (m *SBattleInfo) String() string { return proto.CompactTextString(m) }
func (*SBattleInfo) ProtoMessage()    {}
func (*SBattleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_e8ba8674d9e30b63, []int{15}
}
func (m *SBattleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SBattleInfo.Unmarshal(m, b)
}
func (m *SBattleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SBattleInfo.Marshal(b, m, deterministic)
}
func (dst *SBattleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SBattleInfo.Merge(dst, src)
}
func (m *SBattleInfo) XXX_Size() int {
	return xxx_messageInfo_SBattleInfo.Size(m)
}
func (m *SBattleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SBattleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SBattleInfo proto.InternalMessageInfo

func (m *SBattleInfo) GetBid() int32 {
	if m != nil && m.Bid != nil {
		return *m.Bid
	}
	return 0
}

func (m *SBattleInfo) GetList() []*PBattleObj {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *SBattleInfo) GetIsStart() int32 {
	if m != nil && m.IsStart != nil {
		return *m.IsStart
	}
	return 0
}

func (m *SBattleInfo) GetOwnWeapons() []*PWeapon {
	if m != nil {
		return m.OwnWeapons
	}
	return nil
}

func (m *SBattleInfo) GetOwnItems() []*PItem {
	if m != nil {
		return m.OwnItems
	}
	return nil
}

func (m *SBattleInfo) GetTimeStart() uint32 {
	if m != nil && m.TimeStart != nil {
		return *m.TimeStart
	}
	return 0
}

// 战场物品/武器等
type PBattleObj struct {
	Id                   *uint32         `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	BaseId               *uint32         `protobuf:"varint,2,opt,name=baseId" json:"baseId,omitempty"`
	Type                 *EBattleObjType `protobuf:"varint,3,req,name=type,enum=mproto.EBattleObjType" json:"type,omitempty"`
	X                    *uint32         `protobuf:"varint,4,req,name=x" json:"x,omitempty"`
	Y                    *uint32         `protobuf:"varint,5,req,name=y" json:"y,omitempty"`
	Wear                 *uint32         `protobuf:"varint,6,opt,name=wear" json:"wear,omitempty"`
	Owner                *uint32         `protobuf:"varint,7,opt,name=owner" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PBattleObj) Reset()         { *m = PBattleObj{} }
func (m *PBattleObj) String() string { return proto.CompactTextString(m) }
func (*PBattleObj) ProtoMessage()    {}
func (*PBattleObj) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_e8ba8674d9e30b63, []int{16}
}
func (m *PBattleObj) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBattleObj.Unmarshal(m, b)
}
func (m *PBattleObj) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBattleObj.Marshal(b, m, deterministic)
}
func (dst *PBattleObj) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBattleObj.Merge(dst, src)
}
func (m *PBattleObj) XXX_Size() int {
	return xxx_messageInfo_PBattleObj.Size(m)
}
func (m *PBattleObj) XXX_DiscardUnknown() {
	xxx_messageInfo_PBattleObj.DiscardUnknown(m)
}

var xxx_messageInfo_PBattleObj proto.InternalMessageInfo

func (m *PBattleObj) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PBattleObj) GetBaseId() uint32 {
	if m != nil && m.BaseId != nil {
		return *m.BaseId
	}
	return 0
}

func (m *PBattleObj) GetType() EBattleObjType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return EBattleObjType_OBJ_UNIT
}

func (m *PBattleObj) GetX() uint32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *PBattleObj) GetY() uint32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *PBattleObj) GetWear() uint32 {
	if m != nil && m.Wear != nil {
		return *m.Wear
	}
	return 0
}

func (m *PBattleObj) GetOwner() uint32 {
	if m != nil && m.Owner != nil {
		return *m.Owner
	}
	return 0
}

// 枪属性
type PWeapon struct {
	WeaponId             *int32   `protobuf:"varint,1,req,name=weapon_id,json=weaponId" json:"weapon_id,omitempty"`
	IsEquip              *int32   `protobuf:"varint,2,req,name=is_equip,json=isEquip" json:"is_equip,omitempty"`
	BulletNum            *int32   `protobuf:"varint,3,req,name=bullet_num,json=bulletNum" json:"bullet_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PWeapon) Reset()         { *m = PWeapon{} }
func (m *PWeapon) String() string { return proto.CompactTextString(m) }
func (*PWeapon) ProtoMessage()    {}
func (*PWeapon) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_e8ba8674d9e30b63, []int{17}
}
func (m *PWeapon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PWeapon.Unmarshal(m, b)
}
func (m *PWeapon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PWeapon.Marshal(b, m, deterministic)
}
func (dst *PWeapon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PWeapon.Merge(dst, src)
}
func (m *PWeapon) XXX_Size() int {
	return xxx_messageInfo_PWeapon.Size(m)
}
func (m *PWeapon) XXX_DiscardUnknown() {
	xxx_messageInfo_PWeapon.DiscardUnknown(m)
}

var xxx_messageInfo_PWeapon proto.InternalMessageInfo

func (m *PWeapon) GetWeaponId() int32 {
	if m != nil && m.WeaponId != nil {
		return *m.WeaponId
	}
	return 0
}

func (m *PWeapon) GetIsEquip() int32 {
	if m != nil && m.IsEquip != nil {
		return *m.IsEquip
	}
	return 0
}

func (m *PWeapon) GetBulletNum() int32 {
	if m != nil && m.BulletNum != nil {
		return *m.BulletNum
	}
	return 0
}

// 物品属性
type PItem struct {
	BaseId               *int32   `protobuf:"varint,1,req,name=base_id,json=baseId" json:"base_id,omitempty"`
	Num                  *int32   `protobuf:"varint,2,req,name=num" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PItem) Reset()         { *m = PItem{} }
func (m *PItem) String() string { return proto.CompactTextString(m) }
func (*PItem) ProtoMessage()    {}
func (*PItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_e8ba8674d9e30b63, []int{18}
}
func (m *PItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PItem.Unmarshal(m, b)
}
func (m *PItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PItem.Marshal(b, m, deterministic)
}
func (dst *PItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PItem.Merge(dst, src)
}
func (m *PItem) XXX_Size() int {
	return xxx_messageInfo_PItem.Size(m)
}
func (m *PItem) XXX_DiscardUnknown() {
	xxx_messageInfo_PItem.DiscardUnknown(m)
}

var xxx_messageInfo_PItem proto.InternalMessageInfo

func (m *PItem) GetBaseId() int32 {
	if m != nil && m.BaseId != nil {
		return *m.BaseId
	}
	return 0
}

func (m *PItem) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

// 3005
type CBattleLoaded struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CBattleLoaded) Reset()         { *m = CBattleLoaded{} }
func (m *CBattleLoaded) String() string { return proto.CompactTextString(m) }
func (*CBattleLoaded) ProtoMessage()    {}
func (*CBattleLoaded) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_e8ba8674d9e30b63, []int{19}
}
func (m *CBattleLoaded) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CBattleLoaded.Unmarshal(m, b)
}
func (m *CBattleLoaded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CBattleLoaded.Marshal(b, m, deterministic)
}
func (dst *CBattleLoaded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CBattleLoaded.Merge(dst, src)
}
func (m *CBattleLoaded) XXX_Size() int {
	return xxx_messageInfo_CBattleLoaded.Size(m)
}
func (m *CBattleLoaded) XXX_DiscardUnknown() {
	xxx_messageInfo_CBattleLoaded.DiscardUnknown(m)
}

var xxx_messageInfo_CBattleLoaded proto.InternalMessageInfo

// 3006
// 发射者通知服务器谁被击中了
type CBattleHurt struct {
	BulletId             *int32   `protobuf:"varint,1,req,name=bullet_id,json=bulletId" json:"bullet_id,omitempty"`
	PlayerBattleId       *int32   `protobuf:"varint,2,req,name=player_battle_id,json=playerBattleId" json:"player_battle_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CBattleHurt) Reset()         { *m = CBattleHurt{} }
func (m *CBattleHurt) String() string { return proto.CompactTextString(m) }
func (*CBattleHurt) ProtoMessage()    {}
func (*CBattleHurt) Descriptor() ([]byte, []int) {
	return fileDescriptor_shin_e8ba8674d9e30b63, []int{20}
}
func (m *CBattleHurt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CBattleHurt.Unmarshal(m, b)
}
func (m *CBattleHurt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CBattleHurt.Marshal(b, m, deterministic)
}
func (dst *CBattleHurt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CBattleHurt.Merge(dst, src)
}
func (m *CBattleHurt) XXX_Size() int {
	return xxx_messageInfo_CBattleHurt.Size(m)
}
func (m *CBattleHurt) XXX_DiscardUnknown() {
	xxx_messageInfo_CBattleHurt.DiscardUnknown(m)
}

var xxx_messageInfo_CBattleHurt proto.InternalMessageInfo

func (m *CBattleHurt) GetBulletId() int32 {
	if m != nil && m.BulletId != nil {
		return *m.BulletId
	}
	return 0
}

func (m *CBattleHurt) GetPlayerBattleId() int32 {
	if m != nil && m.PlayerBattleId != nil {
		return *m.PlayerBattleId
	}
	return 0
}

func init() {
	proto.RegisterType((*CPlayerLogin)(nil), "mproto.c_player_login")
	proto.RegisterType((*SPlayerLogin)(nil), "mproto.s_player_login")
	proto.RegisterType((*CServerTime)(nil), "mproto.c_server_time")
	proto.RegisterType((*SServerTime)(nil), "mproto.s_server_time")
	proto.RegisterType((*CLobbyEnter)(nil), "mproto.c_lobby_enter")
	proto.RegisterType((*SLobbyEnter)(nil), "mproto.s_lobby_enter")
	proto.RegisterType((*CLobbyMutch)(nil), "mproto.c_lobby_mutch")
	proto.RegisterType((*SLobbyMutch)(nil), "mproto.s_lobby_mutch")
	proto.RegisterType((*CLobbyCancel)(nil), "mproto.c_lobby_cancel")
	proto.RegisterType((*SLobbyCancel)(nil), "mproto.s_lobby_cancel")
	proto.RegisterType((*CPlayerInfo)(nil), "mproto.c_player_info")
	proto.RegisterType((*SPlayerInfo)(nil), "mproto.s_player_info")
	proto.RegisterType((*CPlayerFrame)(nil), "mproto.c_player_frame")
	proto.RegisterType((*SPlayerFrame)(nil), "mproto.s_player_frame")
	proto.RegisterType((*CBattleStart)(nil), "mproto.c_battle_start")
	proto.RegisterType((*SBattleInfo)(nil), "mproto.s_battle_info")
	proto.RegisterType((*PBattleObj)(nil), "mproto.p_battle_obj")
	proto.RegisterType((*PWeapon)(nil), "mproto.p_weapon")
	proto.RegisterType((*PItem)(nil), "mproto.p_item")
	proto.RegisterType((*CBattleLoaded)(nil), "mproto.c_battle_loaded")
	proto.RegisterType((*CBattleHurt)(nil), "mproto.c_battle_hurt")
	proto.RegisterEnum("mproto.ECode", ECode_name, ECode_value)
	proto.RegisterEnum("mproto.EShinGender", EShinGender_name, EShinGender_value)
	proto.RegisterEnum("mproto.EBattleObjType", EBattleObjType_name, EBattleObjType_value)
}

func init() { proto.RegisterFile("shin.proto", fileDescriptor_shin_e8ba8674d9e30b63) }

var fileDescriptor_shin_e8ba8674d9e30b63 = []byte{
	// 847 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xae, 0x9d, 0x9f, 0x26, 0xa7, 0x89, 0xeb, 0x8e, 0xba, 0xe0, 0x05, 0x21, 0xa2, 0xb9, 0x21,
	0x2a, 0xda, 0x6a, 0x59, 0x10, 0x17, 0xdc, 0xb5, 0xda, 0x80, 0x8c, 0xd2, 0x14, 0x0d, 0x2d, 0x7b,
	0x69, 0x39, 0xf1, 0xa4, 0x35, 0x6b, 0x7b, 0x8c, 0x3d, 0xd9, 0x34, 0xcf, 0xc3, 0x25, 0x6f, 0xc1,
	0xbb, 0xf0, 0x1e, 0xe8, 0x9c, 0x19, 0xd7, 0x5e, 0x21, 0xae, 0x3c, 0xdf, 0x77, 0xe6, 0x3b, 0x73,
	0x7e, 0x0d, 0x50, 0x3f, 0xa6, 0xc5, 0x65, 0x59, 0x29, 0xad, 0xd8, 0x30, 0xa7, 0x2f, 0xff, 0x1e,
	0xbc, 0x4d, 0x54, 0x66, 0xf1, 0x41, 0x56, 0x51, 0xa6, 0x1e, 0xd2, 0x82, 0x9d, 0xc3, 0x40, 0xab,
	0xf7, 0xb2, 0x08, 0x9c, 0x99, 0x3b, 0x1f, 0x0b, 0x03, 0x98, 0x07, 0x6e, 0xb9, 0x0d, 0x5c, 0xa2,
	0xdc, 0x72, 0xcb, 0xbf, 0x03, 0xaf, 0xfe, 0x58, 0xc7, 0xa1, 0xbf, 0x51, 0x89, 0x24, 0x99, 0xf7,
	0xc6, 0xbb, 0x34, 0x0f, 0x5c, 0xca, 0x08, 0x59, 0x41, 0x36, 0x7e, 0x0a, 0xd3, 0x4d, 0x54, 0xcb,
	0xea, 0x83, 0xac, 0x22, 0x9d, 0xe6, 0x92, 0xbf, 0x86, 0x69, 0xdd, 0x25, 0xd8, 0x97, 0x70, 0xd2,
	0x81, 0xe4, 0xac, 0x2f, 0xc0, 0x50, 0x77, 0xa8, 0x20, 0x17, 0x99, 0x5a, 0xaf, 0x0f, 0x91, 0x2c,
	0xb4, 0xac, 0xf8, 0x1c, 0x5d, 0x74, 0x08, 0xf6, 0x29, 0x1c, 0x57, 0x4a, 0xe5, 0x51, 0x9a, 0x90,
	0x7c, 0x20, 0x86, 0x08, 0xc3, 0xa4, 0x2b, 0xcd, 0x77, 0x7a, 0xf3, 0xc8, 0xbf, 0x6a, 0xa5, 0x44,
	0xb0, 0x4f, 0x60, 0x58, 0xc9, 0x7a, 0x97, 0x69, 0x52, 0x4e, 0x85, 0x45, 0xdc, 0xc7, 0x2a, 0x99,
	0x8b, 0x9b, 0xb8, 0xd8, 0xc8, 0x8c, 0xcf, 0x31, 0xff, 0x2e, 0xf3, 0xbf, 0x5a, 0x7a, 0xd5, 0x56,
	0x2a, 0x2d, 0xb6, 0x8a, 0xff, 0xed, 0xe0, 0xb3, 0x1d, 0x86, 0x7d, 0x0e, 0xe3, 0x06, 0x26, 0x56,
	0x3d, 0x32, 0x44, 0x98, 0x60, 0x45, 0xac, 0xb1, 0x88, 0x73, 0x69, 0x5b, 0x00, 0x86, 0x5a, 0xc5,
	0xb9, 0x64, 0xaf, 0x60, 0xf8, 0x20, 0x8b, 0x44, 0x56, 0x41, 0x8f, 0x4a, 0xff, 0xa2, 0x2d, 0x3d,
	0x36, 0x3c, 0x32, 0x46, 0x61, 0x2f, 0x61, 0x9c, 0xf1, 0x87, 0x58, 0xc7, 0x55, 0xd0, 0x37, 0x71,
	0x1a, 0xc4, 0x5e, 0x40, 0xff, 0x41, 0x65, 0x49, 0x30, 0x98, 0x39, 0xf3, 0xe9, 0x0f, 0xce, 0x6b,
	0x41, 0x90, 0x68, 0x99, 0xd7, 0xc1, 0xb0, 0xa5, 0x65, 0x5e, 0xf3, 0x59, 0x67, 0x6e, 0xb6, 0x15,
	0x86, 0xe1, 0x81, 0xab, 0x4a, 0x8a, 0x7e, 0x22, 0x5c, 0x55, 0xf2, 0x3f, 0x9d, 0xce, 0x88, 0x98,
	0x2b, 0xe7, 0x30, 0xd8, 0x15, 0xa9, 0xae, 0x03, 0x67, 0xe6, 0xcc, 0x27, 0xc2, 0x00, 0x4c, 0x50,
	0x3e, 0xe9, 0x2a, 0x8e, 0x8c, 0xcd, 0x25, 0x1b, 0x10, 0x75, 0x4f, 0x17, 0xce, 0x61, 0x90, 0x6a,
	0x8c, 0xa1, 0x67, 0x64, 0x04, 0x58, 0x00, 0xc7, 0x7b, 0x19, 0x97, 0xaa, 0xa8, 0x83, 0x3e, 0xf1,
	0x0d, 0x44, 0xcb, 0x7a, 0x97, 0x65, 0x52, 0xd7, 0x94, 0xcc, 0x44, 0x34, 0x90, 0xf9, 0xd0, 0x53,
	0x65, 0x1d, 0x8c, 0x88, 0xc5, 0xa3, 0xe9, 0xec, 0x3a, 0xd6, 0x3a, 0x93, 0x51, 0xad, 0xe3, 0x4a,
	0xf3, 0x7f, 0xa8, 0x3d, 0x96, 0xa2, 0xf6, 0xf8, 0xd0, 0x5b, 0x3f, 0x0f, 0x13, 0x1e, 0xd9, 0x1c,
	0xfa, 0x59, 0x5a, 0xeb, 0xc0, 0x9d, 0xf5, 0xe6, 0x27, 0x6f, 0xce, 0x9b, 0x82, 0x97, 0x8d, 0x4c,
	0xad, 0x7f, 0x17, 0x74, 0x83, 0xbd, 0x84, 0x51, 0x5a, 0x1b, 0xcf, 0xd4, 0x9e, 0x81, 0x38, 0x4e,
	0xeb, 0x5f, 0x11, 0xb2, 0x6f, 0xe0, 0x44, 0xed, 0x8b, 0xa8, 0x4d, 0x02, 0x7d, 0xf9, 0xad, 0x2f,
	0x63, 0x10, 0xa0, 0xf6, 0xc5, 0x3b, 0x9b, 0xd9, 0xd7, 0x30, 0x46, 0x89, 0xa9, 0xc6, 0x80, 0x04,
	0x5e, 0x2b, 0x40, 0x5a, 0x8c, 0xd4, 0xbe, 0x08, 0xa9, 0x40, 0x5f, 0x00, 0xe0, 0x0e, 0xd9, 0xc7,
	0x8f, 0xb1, 0x7f, 0x62, 0x8c, 0x0c, 0x3d, 0xcf, 0xff, 0x72, 0x60, 0xd2, 0x0d, 0x18, 0x1b, 0xf8,
	0x3c, 0x7e, 0x6e, 0x9a, 0xe0, 0xa0, 0xac, 0xe3, 0x5a, 0x86, 0x09, 0xb5, 0x64, 0x2a, 0x2c, 0x62,
	0xaf, 0xa0, 0xaf, 0x0f, 0xa5, 0xb4, 0xd3, 0xf6, 0xb2, 0x9d, 0xb6, 0xd6, 0x57, 0x84, 0x17, 0x04,
	0x5d, 0x63, 0x13, 0x70, 0x9e, 0xec, 0xa8, 0x39, 0x4f, 0x88, 0x0e, 0xc1, 0xc0, 0xa0, 0x03, 0x63,
	0xd0, 0xdf, 0xcb, 0xb8, 0x32, 0xc3, 0x25, 0xe8, 0x8c, 0xdd, 0x56, 0xfb, 0x42, 0x56, 0x36, 0x62,
	0x03, 0x78, 0x0c, 0xa3, 0xa6, 0x22, 0xb8, 0x2e, 0xe6, 0xd4, 0xae, 0xf8, 0xc8, 0x10, 0x61, 0x62,
	0x0b, 0x2e, 0xff, 0xd8, 0xa5, 0x25, 0xed, 0x0a, 0x15, 0x7c, 0x81, 0x10, 0x0b, 0x62, 0x06, 0x21,
	0x2a, 0x76, 0xb9, 0xed, 0xc6, 0xd8, 0x30, 0xab, 0x5d, 0xce, 0xbf, 0x85, 0xa1, 0xa9, 0x21, 0xfe,
	0x41, 0x30, 0xd7, 0xce, 0x1f, 0xc4, 0xa6, 0xee, 0x43, 0x0f, 0xa5, 0xc6, 0x2f, 0x1e, 0xf9, 0x19,
	0x9c, 0x3e, 0xcf, 0x4f, 0xa6, 0xe2, 0x44, 0x26, 0xfc, 0x37, 0x5c, 0x78, 0x4b, 0x3d, 0xee, 0x2a,
	0x8d, 0xf1, 0xda, 0x77, 0xdb, 0x78, 0x0d, 0x11, 0xe2, 0x28, 0xf9, 0x76, 0x47, 0x9a, 0x91, 0x4b,
	0xac, 0x7f, 0xcf, 0xf0, 0xd7, 0x44, 0x87, 0xc9, 0xc5, 0x67, 0x30, 0x34, 0x3f, 0x53, 0x36, 0x04,
	0x57, 0xbd, 0xf7, 0x8f, 0xd8, 0x08, 0xfa, 0xdb, 0x38, 0xcd, 0x7c, 0xe7, 0xe2, 0x2d, 0x4c, 0x3f,
	0xda, 0x76, 0x76, 0x0a, 0x27, 0x3f, 0x2d, 0x56, 0x6f, 0x17, 0x22, 0x5a, 0xdd, 0x2f, 0x97, 0xfe,
	0x51, 0x87, 0xb8, 0xb9, 0x5a, 0x2e, 0x7c, 0x87, 0x9d, 0xc1, 0xd4, 0x12, 0x3f, 0x2e, 0x6e, 0xae,
	0xc2, 0xa5, 0xef, 0x5e, 0xdc, 0xc2, 0xd9, 0x7f, 0xba, 0xc8, 0x26, 0x30, 0xba, 0xbd, 0xfe, 0x39,
	0xba, 0x5f, 0x85, 0x77, 0xfe, 0x11, 0xf3, 0x00, 0x10, 0xbd, 0x5b, 0x5c, 0xfd, 0x72, 0xbb, 0xf2,
	0x9d, 0xc6, 0x1a, 0xde, 0x2d, 0x6e, 0x7c, 0xb7, 0xb1, 0x5e, 0xdf, 0x2f, 0x97, 0x8b, 0x3b, 0xbf,
	0xf7, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x79, 0x4b, 0xc0, 0x72, 0x06, 0x00, 0x00,
}
